name: Build docker release

on:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Make docker image tag
      id: prepare
      run: |
        export VERSION=${GITHUB_REF#refs/tags/}
        echo "${GITHUB_REF}"
        echo "${VERSION}"
        TAG="iliadmitriev/mailcatcher:${VERSION}"
        TAGS="${TAG},iliadmitriev/mailcatcher:latest"
        echo ::set-output name=tags::${TAGS}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.prepare.outputs.tags }}
